services:
  postgres:
    image: 'postgres:18-alpine3.23'
    environment:
      - 'POSTGRES_DB=postalcode'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=passw0rd'
    ports:
      - '5432:5432'